project_id = "kilpufxhteouojcyzqto"

[functions.customer-send-otp]
verify_jwt = false

[functions.customer-verify-otp]
verify_jwt = false

[functions.customer-signup]
verify_jwt = false

[functions.customer-validate-session]
verify_jwt = false
